title: Minimal theme
logo: /assets/img/https://i.gyazo.com/3825bf12dec5ebf73f56601b8a67d600.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
